apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}
    spec:
      containers:
      - name: web-traackr
        image: localhost:32000/traackr:latest
        ports:
        - containerPort: 80

